# Generated by Django 5.1.4 on 2024-12-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlaccess',
            old_name='url',
            new_name='shortened_url',
        ),
    ]
